.TH SECRET 1
.SH NAME
secret \- Send AES encrypted files via ICMP tunneling
.SH SYNOPSIS
.B secret
\fB\-r\fR \fIfile\fR
\fB\-s\fR \fIhost\fR
|
[\fB\-l\fR]
.SH OPTIONS
.TP
.BR \fB\-r\fR\fI file\fR
The file to be sent.
.TP
.BR \fB\-s\fR\fI host\fR
Recipients IP address or hostname.
.TP
.BR \fB\-l\fR
Run in server mode.
.SH DESCRIPTION
Project variant 2 for ISA 2021.
Secret sends AES-128 encrypted files using SecretProto over ICMP(v6). The program may require elevated priviledges for work with raw sockets.
.SH AUTHOR
Denis Dzibela xdzibe00
.SH FILE MANIFEST
.TP
.B source files
client.hpp
icmp.hpp
mtu.hpp
optArgs.hpp
server.hpp
sll.hpp
clinet.cpp
main.cpp
server.cpp
.TP
.B utility files
Makefile
.TP
.B documentation
secret.1
manual.pdf