.TH SECRET 1
.SH NAME
secret \- Send AES encrypted files via ICMP tunneling
.SH SYNOPSIS
.B secret
\fB\-r\fR \fIfile\fR
\fB\-s\fR \fIhost\fR
|
[\fB\-l\fR]
.SH DESCRIPTION
.SH OPTIONS
.TP
.BR \fB\-r\fR\fI file\fR
The file to be sent.
.TP
.BR \fB\-s\fR\fI host\fR
Recipients IP address or hostname.
.TP
.BR \fB\-l\fR
Run in server mode.
.SH AUTHOR
Denis Dzibela xdzibe00